# Generated by Django 3.2.5 on 2021-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_suspend_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pickup_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_status',
            field=models.BooleanField(null=True),
        ),
    ]
